AllCops:
  NewCops: enable
  TargetRubyVersion: '2.7'

# What in the actual fuck Rubocop.
Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/MethodLength:
  Max: 50
